### ISSUE TITLE
Issues with interpolating array like data with specific arguments

### ISSUE THREAD

**Issue by LuisSanchez25** [XENONnT/xedocs#89]
* xedocs version: 0.2.20
* Python version: 3.8.13
* Operating System: Linux

### Description

Interpolation seems to not be working with array corrections for a particular combination of arguments.

### What I Did

```
run_id = '048025' # this is an example I tested it with several run_ids
xd_db.pmt_area_to_pes.find_df(detector='tpc', version = 'v6', run_id = run_id) #returns an empty dataframe
xd_db.pmt_area_to_pes.find_df(detector='tpc', version = 'v6', run_id = run_id, pmt = 0) #returns the requested data
xd_db.pmt_area_to_pes.find_df(detector='tpc', version = 'v6')# also returns the requested data.

```
Using precise times of the data if it exists in the database also leads to the correct behaviour. So it seems like the issue is with the interpolation of the data.

**Comment by jmosbacher** [comment]
Thanks, this works correctly if you pass `sort=pmt`, which you need to do since the plugin expects the array to be sorted by pmt.
 It is a bug in rframe that it cannot handle unsorted data but it shouldn't affect us since you need to explicitly sort when collecting data that is converted to an array.
